version: '3'

services:
  # message-service:
  #   build: .
  #   container_name: message-service
  #   image: the-message
  #   ports:
  #     - "8080:8080"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"